/**
 * Euler Project - Problem 2:
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 */
/**
 * @author crumble
 * 27-Feb-2015
 */
public class Problem002 {

	public static void main(String args[]) {
		{
			
			long start = System.currentTimeMillis();
			
			int fib1 = 0;
	        int fib2 = 0;
	        int curFib = 1;
	        int sum = 0;
	        while(curFib < 1000000){
	            if(curFib % 2 == 0){
	                sum += curFib;
	            }
	            fib1 = fib2;
	            fib2 = curFib;
	            curFib = fib1 + fib2;
	        }
	        System.out.println("Solution to Euler Problem 2 = " + sum);

			long stop = System.currentTimeMillis();
			System.out.println(stop-start + "ms");
		}
	}
}